Android_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Android App Development" fancy_textbox_subtitle="" fancy_textbox_content="It is the app development that we work in and we try to incorporate features and ideas as much as we can." fancy_textbox_image="5647" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fandroid-app-development-company-dubai%2F"]'
Mobile_App_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Mobile App Development" fancy_textbox_subtitle="" fancy_textbox_content="we are helping the companies to thrive and make a better grip in their businesses. Our motive is to present a well-equipped mobile application, to flag the industry." fancy_textbox_image="7337" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fmobile-app-development-company%2F"]'
IOS_App_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="IOS App Development" fancy_textbox_subtitle="" fancy_textbox_content="It is a type of app development that requires Objective C or swift language for its code to be written. It is the second most wanted app to be required." fancy_textbox_image="7335" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fios-app-development%2F|title:IOS%20App%20Development"]'
Hybrid_App_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Hybrid App Development" fancy_textbox_subtitle="" fancy_textbox_content="Building apps on cross-platforms is inexpensive and it can run on multiple platforms. It is one type of mobile app development." fancy_textbox_image="7335" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.com%2Fhybrid-app-development%2F"]'
Education_App_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Educational App" fancy_textbox_subtitle="" fancy_textbox_content="Educational app development solutions offer great opportunities for the education sector to use a single application to deliver different learning activities in a compact manner." fancy_textbox_image="7506" extra_class="font-weight-regular" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Feducation-app-development%2F|title:Education%20App%20Development"]'
Entertainment_Music_App = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Entertainment & Music App" fancy_textbox_subtitle="" fancy_textbox_content="Ajath\'s intelligent media management redefine the way media and entertainment industry benefit from new generation technology" fancy_textbox_image="5334" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fentertainment-and-music-app-solutions%2F|title:Entertainment%20%26%20Music%20App"]'
Food_Ordering_App = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Food Ordering App" fancy_textbox_subtitle="" fancy_textbox_content="Design and develop on-demand food delivery apps like Zomato, Swiggy or UberEats that come preloaded with powerful features and advanced technology." fancy_textbox_image="7505" extra_class="font-weight-regular" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Ffood-ordering-app%2F|title:Food%20Ordering%20App"]'
Healthcare_App = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Healthcare App" fancy_textbox_subtitle="" fancy_textbox_content="Our Healthcare app solution is focused on gaining tangible results for the customers while ensuring app quality and security." fancy_textbox_image="7513" extra_class="font-weight-regular" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fhealthcare-app%2F|title:Healthcare%20App"]'
IoT_in_Healthcare = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="IoT in Healthcare" fancy_textbox_subtitle="" fancy_textbox_content="We design innovative medical IoT solutions that help you deliver superior medical services/care, advance research and innovation." fancy_textbox_image="7499" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fiot-in-healthcare%2F|title:IoT%20in%20Healthcare"]'
Cab_Taxi_Solutions = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Cab Taxi Solutions" fancy_textbox_subtitle="" fancy_textbox_content="Take your taxi business online and grow globally with an easy-to-use on-demand taxi dispatch solution that can be customized to  your business needs, from ideation to app store launch ." fancy_textbox_image="7509" extra_class="font-weight-regular" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fcab-taxi-solutions%2F|title:Cab%20%26%20Taxi%20Solutions"]'
Manufacturing_Solution = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Manufacturing Solutions" fancy_textbox_subtitle="" fancy_textbox_content="We provide our customers with unique and intuitive manufacturing solutions  and realize their full potential." fancy_textbox_image="7500" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fmanufacturing-solution%2F|title:Manufacturing%20Solution"]'
Web_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Web Development" fancy_textbox_subtitle="" fancy_textbox_content="It provides web development services including arrangement reconciliation and seaward." fancy_textbox_image="5628" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fweb-development-company-dubai%2F"]'
E_Commerce = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="E-commerce Solutions" fancy_textbox_subtitle="" fancy_textbox_content="E-commerce solutions is one of the hottest sectors in technological transformation, enabling organizations  to generate new revenue streams from customers globally," fancy_textbox_image="7497" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fe-commerce-soluions%2F|title:E-Commerce"]'
Digital_Marketing = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Digital Marketing" fancy_textbox_subtitle="" fancy_textbox_content="Best digital marketing agency in Dubai which provides spite of having the skills, capacity, and pervasiveness." fancy_textbox_image="7338" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fdigital-marketing-services-in-uae%2F"]'
Advertising_Solution = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Advertising Solutions" fancy_textbox_subtitle="" fancy_textbox_content="Advertising Solutions are an effective option to help small businesses and startups with these challenges reach more potential customers and generate more revenue.." fancy_textbox_image="7496" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fadvertising-solution%2F|title:Advertising%20Solution"]'
Native_App_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Native App Development" fancy_textbox_subtitle="" fancy_textbox_content="It is a type of app development that is expensive and it runs on only one platform. That is its specialty. The code is written again whenever it is tried on any platform." fancy_textbox_image="5646" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.com%2Freact-native-app-development-services%2F"]'
Custom_App_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Custom App Development" fancy_textbox_subtitle="" fancy_textbox_content="Our expertise lies in providing a custom mobile app, and many of our clients have utilized this service." fancy_textbox_image="5628" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.com%2Fcustom-app-development-service%2F"]'


# Android_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Android App Development" fancy_textbox_subtitle="" fancy_textbox_content="It is the app development that we work in and we try to incorporate features and ideas as much as we can." fancy_textbox_image="5647" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fandroid-app-development-company-dubai%2F"]'
# Mobile_App_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Mobile App Development" fancy_textbox_subtitle="" fancy_textbox_content="we are helping the companies to thrive and make a better grip in their businesses. Our motive is to present a well-equipped mobile application, to flag the industry." fancy_textbox_image="7337" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fmobile-app-development-company%2F"]'
# IOS_App_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="IOS App Development" fancy_textbox_subtitle="" fancy_textbox_content="It is a type of app development that requires Objective C or swift language for its code to be written. It is the second most wanted app to be required." fancy_textbox_image="7335" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fios-app-development%2F|title:IOS%20App%20Development"]'
# Hybrid_App_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Hybrid App Development" fancy_textbox_subtitle="" fancy_textbox_content="Building apps on cross-platforms is inexpensive and it can run on multiple platforms. It is one type of mobile app development." fancy_textbox_image="7335" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.com%2Fhybrid-app-development%2F"]'
# Education_App_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Educational App" fancy_textbox_subtitle="" fancy_textbox_content="Educational app development solutions offer great opportunities for the education sector to use a single application to deliver different learning activities in a compact manner." fancy_textbox_image="7506" extra_class="font-weight-regular" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Feducation-app-development%2F|title:Education%20App%20Development"]'
# Entertainment_Music_App = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Entertainment & Music App" fancy_textbox_subtitle="" fancy_textbox_content="Ajath's intelligent media management redefine the way media and entertainment industry benefit from new generation technology" fancy_textbox_image="5334" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fentertainment-and-music-app-solutions%2F|title:Entertainment%20%26%20Music%20App"]'
# Food_Ordering_App = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Food Ordering App" fancy_textbox_subtitle="" fancy_textbox_content="Design and develop on-demand food delivery apps like Zomato, Swiggy or UberEats that come preloaded with powerful features and advanced technology." fancy_textbox_image="7505" extra_class="font-weight-regular" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Ffood-ordering-app%2F|title:Food%20Ordering%20App"]'
# Healthcare_App = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Healthcare App" fancy_textbox_subtitle="" fancy_textbox_content="Our Healthcare app solution is focused on gaining tangible results for the customers while ensuring app quality and security." fancy_textbox_image="7513" extra_class="font-weight-regular" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fhealthcare-app%2F|title:Healthcare%20App"]'
# IoT_in_Healthcare = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="IoT in Healthcare" fancy_textbox_subtitle="" fancy_textbox_content="We design innovative medical IoT solutions that help you deliver superior medical services/care, advance research and innovation." fancy_textbox_image="7499" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fiot-in-healthcare%2F|title:IoT%20in%20Healthcare"]'
# Cab_Taxi_Solutions = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Cab Taxi Solutions" fancy_textbox_subtitle="" fancy_textbox_content="Take your taxi business online and grow globally with an easy-to-use on-demand taxi dispatch solution that can be customized to  your business needs, from ideation to app store launch ." fancy_textbox_image="7509" extra_class="font-weight-regular" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fcab-taxi-solutions%2F|title:Cab%20%26%20Taxi%20Solutions"]'
# Manufacturing_Solution = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Manufacturing Solutions" fancy_textbox_subtitle="" fancy_textbox_content="We provide our customers with unique and intuitive manufacturing solutions  and realize their full potential." fancy_textbox_image="7500" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fmanufacturing-solution%2F|title:Manufacturing%20Solution"]'
# Web_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Web Development" fancy_textbox_subtitle="" fancy_textbox_content="It provides web development services including arrangement reconciliation and seaward." fancy_textbox_image="5628" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fweb-development-company-dubai%2F"]'
# E_Commerce = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="E-commerce Solutions" fancy_textbox_subtitle="" fancy_textbox_content="E-commerce solutions is one of the hottest sectors in technological transformation, enabling organizations  to generate new revenue streams from customers globally," fancy_textbox_image="7497" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fe-commerce-soluions%2F|title:E-Commerce"]'
# Digital_Marketing = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Digital Marketing" fancy_textbox_subtitle="" fancy_textbox_content="Best digital marketing agency in Dubai which provides spite of having the skills, capacity, and pervasiveness." fancy_textbox_image="7338" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fdigital-marketing-services-in-uae%2F"]'
# Advertising_Solution = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Advertising Solutions" fancy_textbox_subtitle="" fancy_textbox_content="Advertising Solutions are an effective option to help small businesses and startups with these challenges reach more potential customers and generate more revenue.." fancy_textbox_image="7496" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.ae%2Fadvertising-solution%2F|title:Advertising%20Solution"]'
# Native_App_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Native App Development" fancy_textbox_subtitle="" fancy_textbox_content="It is a type of app development that is expensive and it runs on only one platform. That is its specialty. The code is written again whenever it is tried on any platform." fancy_textbox_image="5646" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.com%2Freact-native-app-development-services%2F"]'
# Custom_App_Development = '[rt_fancy_text_box_style style_variation="four" fancy_textbox_title="Custom App Development" fancy_textbox_subtitle="" fancy_textbox_content="Our expertise lies in providing a custom mobile app, and many of our clients have utilized this service." fancy_textbox_image="5628" fancy_textbox_link="url:https%3A%2F%2Fwww.ajath.com%2Fcustom-app-development-service%2F"]'

# print(Custom_App_Development)
# # <!-- Coupon Solutions
# # Consulting
# # Digital Marketing Services
# # Wireframing
# # Product LifeCycle
# # Alexa Skill
# # Bots Development
# # Application Development
# # Security Alarm
# # Doctor Booking Solution
# # Technology
# # Health & Fitness -->

# 'Android_Development', 'Mobile_App_Development', 'IOS_App_Development', 'Hybrid_App_Development', 'Education_App_Development', 'Entertainment_Music_App', 'Food_Ordering_App', 'Healthcare_App', 'IoT_in_Healthcare', 'Cab_Taxi_Solutions', 'Manufacturing_Solution', 'Web_Development', 'E_Commerce', 'Digital_Marketing', 'Advertising_Solution', 'Native_App_Development', 'Custom_App_Development'